### PR TITLE
Adding gettable functions for links

### PR DESCRIPTION
**Pull request by IAmMadfly**
Added pre-processing step in checking if link strings are available for the next pagination.

If there are valid URLs for the next and prev page, then change the URLs to functions for the user to be able to call to get the next/previous page

### CODE REVIEW

**Review by ndench — APPROVED** [review]
This looks pretty good to me. Thanks!

**Comment by ndench** [comment]
You'll just have to rebase onto master to fix the merge conflict @IAmMadfly.

**Comment by IAmMadfly** [comment]
Thanks! :D Fixed the conflict

**Comment by ndench** [comment]
Thanks!

**Pull request merged**
